#!/bin/bash

mkdir datos

cd datos

wget -i http://www.pccomponentes.com/msi_gp62_2qe_203xes_intel_i7_5700hq_8gb_1tb_gtx950m_15_6_.html >> datos

cat pagina_opiniones_usuario.php\?idc\=* >> solucion.txt

DIRECTORIOANTES=$(pwd)

cd ..

DIRECTORIODESPUES=$(pwd)

cp $DIRECTORIOANTES/solucion.txt $DIRECTORIODESPUES

lex practica3.l

g++ lex.yy.c -o prog -lfl

./prog datos/solucion.txt >> final.txt

lex practica3a.l

g++ lex.yy.c -o prog1 -lfl

./prog1 final.txt >> final2.txt




echo "Finalizado"

echo "Abrir final2.txt"
